/**
 * Measure the observed shape of every pipeline artifact on disk.
 *
 * The PR 2 schema-derivation procedure (phase2-closeout spec) is artifact-
 * first: schemas must be generated from observed reality and validate 100%
 * of the existing corpus. This script produces the observation.
 *
 * Usage: npx tsx scripts/measure-artifact-shapes.ts [--out <file.md>]
 */
import { readdirSync, readFileSync, existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { PIPE_DIR } from '../lib/paths.js';

const AGENTS = [
  'researcher', 'data-checker', 'code-checker', 'trade-analyst',
  'summarizer', 'predictor', 'final-review',
] as const;

interface FieldStat {
  /** number of artifacts in which this path appears at least once */
  presentIn: number;
  /** observed JS types across all occurrences (null distinct from object) */
  types: Map<string, number>;
  /** small distinct string values (enum candidates), capped */
  samples: Set<string>;
}

function typeOf(v: unknown): string {
  if (v === null) return 'null';
  if (Array.isArray(v)) return 'array';
  return typeof v;
}

const MAX_DEPTH = 6;
const MAX_SAMPLES = 12;

/** Collect path→types for ONE artifact (each path counted once for presence). */
function walk(value: unknown, path: string, acc: Map<string, { types: Set<string>; samples: Set<string> }>, depth = 0): void {
  if (depth > MAX_DEPTH) return;
  const t = typeOf(value);
  const entry = acc.get(path) ?? { types: new Set<string>(), samples: new Set<string>() };
  entry.types.add(t);
  if (t === 'string' && (value as string).length <= 32 && entry.samples.size < MAX_SAMPLES) {
    entry.samples.add(value as string);
  }
  if (t === 'string' && /^-?\d+(\.\d+)?$/.test(value as string)) {
    entry.types.add('numeric-string'); // string-vs-number drift detector
  }
  acc.set(path, entry);
  if (t === 'object') {
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
      walk(v, path ? `${path}.${k}` : k, acc, depth + 1);
    }
  } else if (t === 'array') {
    for (const item of value as unknown[]) {
      walk(item, `${path}[]`, acc, depth + 1);
    }
  }
}

function main(): void {
  const taskDirs = readdirSync(PIPE_DIR).filter(d => d.startsWith('task-'));
  const report: string[] = [
    '# Artifact shape report',
    '',
    `Generated by scripts/measure-artifact-shapes.ts over ${taskDirs.length} task dirs in pipeline/.`,
    'Input to PR 2 schema derivation — see 2026-06-12-pr2-typed-artifact-reads.md.',
    '',
  ];

  for (const agent of AGENTS) {
    const stats = new Map<string, FieldStat>();
    let total = 0;
    let unparseable = 0;
    for (const dir of taskDirs) {
      const file = join(PIPE_DIR, dir, `${agent}.json`);
      if (!existsSync(file)) continue;
      total++;
      let parsed: unknown;
      try { parsed = JSON.parse(readFileSync(file, 'utf-8')); }
      catch { unparseable++; continue; }
      const local = new Map<string, { types: Set<string>; samples: Set<string> }>();
      walk(parsed, '', local);
      for (const [path, { types, samples }] of local) {
        const s = stats.get(path) ?? { presentIn: 0, types: new Map<string, number>(), samples: new Set<string>() };
        s.presentIn++;
        for (const t of types) s.types.set(t, (s.types.get(t) ?? 0) + 1);
        for (const v of samples) if (s.samples.size < MAX_SAMPLES) s.samples.add(v);
        stats.set(path, s);
      }
    }

    report.push(`## ${agent}.json — ${total} artifacts (${unparseable} unparseable)`, '');
    if (total === 0) { report.push('_none on disk_', ''); continue; }
    report.push('| path | present | types | samples |', '|---|---|---|---|');
    const paths = [...stats.keys()].sort();
    for (const path of paths) {
      if (path === '') continue; // root
      const s = stats.get(path)!;
      const pct = Math.round((s.presentIn / total) * 100);
      const types = [...s.types.keys()].sort().join(', ');
      const samples = [...s.samples].slice(0, 6).map(v => `\`${v.replace(/\|/g, '\\|')}\``).join(' ');
      report.push(`| \`${path}\` | ${s.presentIn}/${total} (${pct}%) | ${types} | ${samples} |`);
    }
    report.push('');
  }

  const outIdx = process.argv.indexOf('--out');
  const outFile = outIdx > -1 ? process.argv[outIdx + 1] : 'docs/superpowers/plans/2026-06-12-artifact-shape-report.md';
  writeFileSync(outFile, report.join('\n'));
  console.log(`wrote ${outFile}`);
}

main();
